server:
  port: 8082
spring:
  application:
    name: foo
  config:
    import: "optional:configserver:"
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
